import Head from "next/head";
import Image from "next/image";
import DayHolder from "components/DayHolder";
import Calendar from "components/Calendar";

export default function Home() {
  let exerciseSession;

  return (
    <div className="main-page">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Calendar/>
      <DayHolder />
    </div>
  );
}
